outdir: "/u/home/j/jzou1115/project-zarlab/CFW/confidence_interval_pipeline_out_pruned"

chromosomes: "data/chromosomes.txt"
phenotypes: "data/phenotypes.txt"
qtls: "/u/home/j/jzou1115/project-zarlab/CFW/confidence_intervals/data/qtls/qtls_decorrelated_threshold3.txt"
kinship: "/u/home/j/jzou1115/project-zarlab/CFW/confidence_interval_pipeline_out/grms/kinship_matrices.Rdata"
scans: "/u/home/j/jzou1115/project-zarlab/CFW/confidence_intervals/output2/scans"
mm: "/u/home/j/jzou1115/project-zarlab/CFW/confidence_intervals/output2"

qtl_ids: "data/qtls_decorrelated_info90_all.txt"

