outdir: "/u/home/j/jzou1115/project-zarlab/CFW/confidence_interval_pipeline_out_pruned_ox"

chromosomes: "data/chromosomes.txt"
phenotypes: "data/phenotypes.txt"
qtls: "/u/home/j/jzou1115/project-zarlab/CFW/confidence_intervals/data/qtls/qtls_decorrelated_threshold_ox.txt"
kinship: "/u/home/j/jzou1115/project-zarlab/CFW/confidence_interval_pipeline_out/grms/kinship_matrices_ox.Rdata"

qtl_ids: "data/qtls_decorrelated_info90_uc.txt"

